const Types = {
	RESIZE_WINDOW: 'RESIZE_WINDOW',
	MOVE_MOUSE: 'MOVE_MOUSE',
	UPDATE_CAMERA_POSITION: 'UPDATE_CAMERA_POSITION',
	UPDATE_MATERIAL_OFFSET: 'UPDATE_MATERIAL_OFFSET',
	INITIALIZE_CURVE: 'INITIALIZE_CURVE',
	UPDATE_CURVE: 'UPDATE_CURVE',
	LOADING: 'LOADING',
	LOADED: 'LOADED',
}
export default Types
