const Types = {
	RESIZE_WINDOW: 'RESIZE_WINDOW',
	UPDATE_CAMERA_POSITION: 'UPDATE_CAMERA_POSITION',
	LOADING: 'LOADING',
	LOADED: 'LOADED',
	PLAY_TIME: 'PLAY_TIME',
	REWIND_TIME: 'REWIND_TIME',
}
export default Types
